#
# cobra MySQL Dockerfile
#

# Pull latest mysql version on debian
FROM mysql:latest

MAINTAINER Sebastian Hof <mail@sebastianhof.com>

# set basic environment variables
ENV MYSQL_ROOT_PASSWORD KEgztLmTKqs2KeMgwi98v3EeeNXoUatgmcJrPQLm
ENV MYSQL_USER coubr
ENV MYSQL_PASSWORD Tub4noC4jUp4oK1gHod6nEef8tHiv3cigHs9iF6z
ENV MYSQL_DATABASE coubr



